// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Automatically detect and process session from URL hash
    // Prevent automatic session refresh on tab focus - only refresh when needed
    // Supabase will still refresh tokens when they're about to expire
    flowType: "pkce", // Use PKCE flow for better security and session management
  },
  global: {
    headers: {
      "x-client-info": "blinno-web",
    },
  },
  // Real-time configuration
  realtime: {
    // Don't reconnect immediately on tab focus - wait for user interaction
    params: {
      eventsPerSecond: 10,
    },
  },
});